spring:
  application:
    name: kakao-api

server:
  port:
    9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s

