
server:
  port:
    9100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement?serverTimezone=Asia/Seoul
    username: sin
    password: sin1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # DB? table ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity? ???? ??? table? ??? ??? ?
      use-new-id-generator-mappings: false # JPA? ??? ??? ???? ??
    show-sql: true # ???? ??? ?, ???? ??
    properties:
      hibernate.format_sql: true # ???? ???? ??
