
server:
  port:
    9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: usermanagement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement?serverTimezone=Asia/Seoul
    username: sin
    password: sin1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # DB? table ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity? ???? ??? table? ??? ??? ?
      use-new-id-generator-mappings: false # JPA? ??? ??? ???? ??
    show-sql: true # ???? ??? ?, ???? ??
    properties:
      hibernate.format_sql: true # ???? ???? ??

  spring:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: group-id-oing
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

